### ISSUE TITLE
Peer-to-Peer Code Review

### ISSUE THREAD

**Issue by Abe1able** [MohamedHNoor/Awsome-booklist#3]
### Hey @MohamedHNoor 👋
Great work on implementing the project requirements.  😊

**Highlights** 🥇
✔️ Following the GitFlow
✔️ Descriptive PR Title
✔️ Descriptive PR Summary
✔️ Following the Requirements

**Improvement suggestions**
In your Add Book and Contact Info pages, the user has to scroll up to get the navigation bar. Kindly fix that for a better user experience. 👍

**Comment by MohamedHNoor** [comment]
sorted
